# Golf data analys 
## 2010 - 2018

In [32]:
import pandas as pd
import matplotlib as plt

df = pd.read_csv('pgaTourData.csv')


df.head()

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2312 entries, 0 to 2311
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player Name         2312 non-null   str
 1   Rounds              1678 non-null   float64
 2   Fairway Percentage  1678 non-null   float64
 3   Year                2312 non-null   int64
 4   Avg Distance        1678 non-null   float64
 5   gir                 1678 non-null   float64
 6   Average Putts       1678 non-null   float64
 7   Average Scrambling  1678 non-null   float64
 8   Average Score       1678 non-null   float64
 9   Points              2296 non-null   str
 10  Wins                293 non-null    float64
 11  Top 10              1458 non-null   float64
 12  Average SG Putts    1678 non-null   float64
 13  Average SG Total    1678 non-null   float64
 14  SG:OTT              1678 non-null   float64
 15  SG:APR              1678 non-null   float64
 16  SG:ARG              1678 non-null   float64
 17  Money               2300 non-null   str
dtypes: float64(14), int64(1), str(3)
memory usage: 325.3 KB

,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG
count,1678.000000,1678.000000,2312.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,293.000000,1458.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000
mean,78.711561,61.440560,2013.996107,290.807688,65.661675,29.163331,58.115638,70.921961,1.218430,2.781893,0.025641,0.148105,0.037759,0.065015,0.019974
std,14.274137,5.058845,2.581176,8.916631,2.745411,0.518468,3.384769,0.698305,0.573443,1.895094,0.343787,0.694923,0.379892,0.380952,0.223361
min,45.000000,43.020000,2010.000000,266.400000,53.540000,27.510000,44.010000,68.698000,1.000000,1.000000,-1.475000,-3.209000,-1.717000,-1.680000,-0.930000
25%,69.000000,57.942500,2012.000000,284.900000,63.830000,28.810000,55.900000,70.494250,1.000000,1.000000,-0.187000,-0.254750,-0.190250,-0.180750,-0.123000
50%,79.500000,61.430000,2014.000000,290.550000,65.790000,29.140000,58.275000,70.902000,1.000000,2.000000,0.040000,0.147000,0.056000,0.081000,0.022000
75%,89.000000,64.910000,2016.000000,296.400000,67.580000,29.520000,60.420000,71.342750,1.000000,4.000000,0.257000,0.568500,0.291500,0.314500,0.175000
max,120.000000,76.880000,2018.000000,319.700000,73.520000,31.000000,69.330000,74.400000,5.000000,14.000000,1.130000,2.406000,1.485000,1.533000,0.660000

## Datatvätt

In [33]:
# 1. Ta bort rader som saknar all spelstatistik
df = df.dropna(subset=['Rounds'])

# 2. Konvertera Money från text till tal
df['Money'] = df['Money'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)
df['Money'] = pd.to_numeric(df['Money'], errors='coerce')

# 3. Konvertera Points från text till tal
df['Points'] = df['Points'].str.replace(',', '', regex=False)
df['Points'] = pd.to_numeric(df['Points'], errors='coerce')

# 4. Fyll i 0 för Wins och Top 10
df['Wins'] = df['Wins'].fillna(0)
df['Top 10'] = df['Top 10'].fillna(0)


df.head()

df.info()

df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Player Name         1678 non-null   str
 1   Rounds              1678 non-null   float64
 2   Fairway Percentage  1678 non-null   float64
 3   Year                1678 non-null   int64
 4   Avg Distance        1678 non-null   float64
 5   gir                 1678 non-null   float64
 6   Average Putts       1678 non-null   float64
 7   Average Scrambling  1678 non-null   float64
 8   Average Score       1678 non-null   float64
 9   Points              1674 non-null   float64
 10  Wins                1678 non-null   float64
 11  Top 10              1678 non-null   float64
 12  Average SG Putts    1678 non-null   float64
 13  Average SG Total    1678 non-null   float64
 14  SG:OTT              1678 non-null   float64
 15  SG:APR              1678 non-null   float64
 16  SG:ARG              1678 non-null   float64
 17  Money               1674 non-null   float64
dtypes: float64(16), int64(1), str(1)
memory usage: 236.1 KB

,Rounds,Fairway Percentage,Year,Avg Distance,gir,Average Putts,Average Scrambling,Average Score,Points,Wins,Top 10,Average SG Putts,Average SG Total,SG:OTT,SG:APR,SG:ARG,Money
count,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1674.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1678.000000,1.674000e+03
mean,78.711561,61.440560,2014.004768,290.807688,65.661675,29.163331,58.115638,70.921961,631.125448,0.206198,2.331943,0.025641,0.148105,0.037759,0.065015,0.019974,1.488682e+06
std,14.274137,5.058845,2.608637,8.916631,2.745411,0.518468,3.384769,0.698305,452.741472,0.516083,2.061388,0.343787,0.694923,0.379892,0.380952,0.223361,1.410333e+06
min,45.000000,43.020000,2010.000000,266.400000,53.540000,27.510000,44.010000,68.698000,3.000000,0.000000,0.000000,-1.475000,-3.209000,-1.717000,-1.680000,-0.930000,2.465000e+04
25%,69.000000,57.942500,2012.000000,284.900000,63.830000,28.810000,55.900000,70.494250,322.000000,0.000000,1.000000,-0.187000,-0.254750,-0.190250,-0.180750,-0.123000,5.656412e+05
50%,79.500000,61.430000,2014.000000,290.550000,65.790000,29.140000,58.275000,70.902000,530.000000,0.000000,2.000000,0.040000,0.147000,0.056000,0.081000,0.022000,1.046144e+06
75%,89.000000,64.910000,2016.000000,296.400000,67.580000,29.520000,60.420000,71.342750,813.750000,0.000000,3.000000,0.257000,0.568500,0.291500,0.314500,0.175000,1.892478e+06
max,120.000000,76.880000,2018.000000,319.700000,73.520000,31.000000,69.330000,74.400000,4169.000000,5.000000,14.000000,1.130000,2.406000,1.485000,1.533000,0.660000,1.203046e+07